/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as PedidosIdPagosRouteImport } from './routes/pedidos.$id_.pagos'
import { Route as PedidosIdNotaRouteImport } from './routes/pedidos.$id_.nota'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdPagosRoute = PedidosIdPagosRouteImport.update({
  id: '/pedidos/$id_/pagos',
  path: '/pedidos/$id/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdNotaRoute = PedidosIdNotaRouteImport.update({
  id: '/pedidos/$id_/nota',
  path: '/pedidos/$id/nota',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/productos': typeof ProductosRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/pedidos/$id/nota': typeof PedidosIdNotaRoute
  '/pedidos/$id/pagos': typeof PedidosIdPagosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/productos': typeof ProductosRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos': typeof PedidosIndexRoute
  '/pedidos/$id/nota': typeof PedidosIdNotaRoute
  '/pedidos/$id/pagos': typeof PedidosIdPagosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/productos': typeof ProductosRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/pedidos/$id_/nota': typeof PedidosIdNotaRoute
  '/pedidos/$id_/pagos': typeof PedidosIdPagosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/productos'
    | '/pedidos/$id'
    | '/pedidos/'
    | '/pedidos/$id/nota'
    | '/pedidos/$id/pagos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/productos'
    | '/pedidos/$id'
    | '/pedidos'
    | '/pedidos/$id/nota'
    | '/pedidos/$id/pagos'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracion'
    | '/productos'
    | '/pedidos/$id'
    | '/pedidos/'
    | '/pedidos/$id_/nota'
    | '/pedidos/$id_/pagos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ProductosRoute: typeof ProductosRoute
  PedidosIdRoute: typeof PedidosIdRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  PedidosIdNotaRoute: typeof PedidosIdNotaRoute
  PedidosIdPagosRoute: typeof PedidosIdPagosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id_/pagos': {
      id: '/pedidos/$id_/pagos'
      path: '/pedidos/$id/pagos'
      fullPath: '/pedidos/$id/pagos'
      preLoaderRoute: typeof PedidosIdPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id_/nota': {
      id: '/pedidos/$id_/nota'
      path: '/pedidos/$id/nota'
      fullPath: '/pedidos/$id/nota'
      preLoaderRoute: typeof PedidosIdNotaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ProductosRoute: ProductosRoute,
  PedidosIdRoute: PedidosIdRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  PedidosIdNotaRoute: PedidosIdNotaRoute,
  PedidosIdPagosRoute: PedidosIdPagosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
